/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.share.ftp;

public class App {
  public String getGreeting() {
    return " welcome to Hell world!!!!! welcome";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
